# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bingo.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x62ingo.proto\x12\x05\x62ingo\"(\n\x13\x41uthenticateRequest\x12\x11\n\tuser_name\x18\x01 \x01(\t\"-\n\x14\x41uthenticateResponse\x12\x15\n\rauthenticated\x18\x01 \x01(\x08\"\x0e\n\x0cReadyRequest\"\x0f\n\rReadyResponse\"\x12\n\x10UserBoardRequest\"\x1c\n\tUserBoard\x12\x0f\n\x07numbers\x18\x01 \x03(\x05\".\n\x14MarkedNumbersRequest\x12\x16\n\x0emarked_numbers\x18\x01 \x03(\x05\"6\n\x15MarkedNumbersResponse\x12\r\n\x05valid\x18\x01 \x01(\x08\x12\x0e\n\x06winner\x18\x02 \x01(\x08\"\x14\n\x12\x44rawnNumberRequest\"\x1d\n\x0b\x44rawnNumber\x12\x0e\n\x06number\x18\x01 \x01(\x05\x32\xd9\x02\n\x0c\x42ingoService\x12G\n\x0c\x41uthenticate\x12\x1a.bingo.AuthenticateRequest\x1a\x1b.bingo.AuthenticateResponse\x12\x32\n\x05Ready\x12\x13.bingo.ReadyRequest\x1a\x14.bingo.ReadyResponse\x12\x39\n\x0cGetUserBoard\x12\x17.bingo.UserBoardRequest\x1a\x10.bingo.UserBoard\x12P\n\x13SubmitMarkedNumbers\x12\x1b.bingo.MarkedNumbersRequest\x1a\x1c.bingo.MarkedNumbersResponse\x12?\n\x0eGetDrawnNumber\x12\x19.bingo.DrawnNumberRequest\x1a\x12.bingo.DrawnNumberb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bingo_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _AUTHENTICATEREQUEST._serialized_start=22
  _AUTHENTICATEREQUEST._serialized_end=62
  _AUTHENTICATERESPONSE._serialized_start=64
  _AUTHENTICATERESPONSE._serialized_end=109
  _READYREQUEST._serialized_start=111
  _READYREQUEST._serialized_end=125
  _READYRESPONSE._serialized_start=127
  _READYRESPONSE._serialized_end=142
  _USERBOARDREQUEST._serialized_start=144
  _USERBOARDREQUEST._serialized_end=162
  _USERBOARD._serialized_start=164
  _USERBOARD._serialized_end=192
  _MARKEDNUMBERSREQUEST._serialized_start=194
  _MARKEDNUMBERSREQUEST._serialized_end=240
  _MARKEDNUMBERSRESPONSE._serialized_start=242
  _MARKEDNUMBERSRESPONSE._serialized_end=296
  _DRAWNNUMBERREQUEST._serialized_start=298
  _DRAWNNUMBERREQUEST._serialized_end=318
  _DRAWNNUMBER._serialized_start=320
  _DRAWNNUMBER._serialized_end=349
  _BINGOSERVICE._serialized_start=352
  _BINGOSERVICE._serialized_end=697
# @@protoc_insertion_point(module_scope)
