# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import bingo_pb2 as bingo__pb2


class BingoServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Authenticate = channel.unary_unary(
                '/bingo.BingoService/Authenticate',
                request_serializer=bingo__pb2.AuthenticateRequest.SerializeToString,
                response_deserializer=bingo__pb2.AuthenticateResponse.FromString,
                )
        self.Ready = channel.unary_unary(
                '/bingo.BingoService/Ready',
                request_serializer=bingo__pb2.ReadyRequest.SerializeToString,
                response_deserializer=bingo__pb2.ReadyResponse.FromString,
                )
        self.GetUserBoard = channel.unary_unary(
                '/bingo.BingoService/GetUserBoard',
                request_serializer=bingo__pb2.UserBoardRequest.SerializeToString,
                response_deserializer=bingo__pb2.UserBoard.FromString,
                )
        self.SubmitMarkedNumbers = channel.unary_unary(
                '/bingo.BingoService/SubmitMarkedNumbers',
                request_serializer=bingo__pb2.MarkedNumbersRequest.SerializeToString,
                response_deserializer=bingo__pb2.MarkedNumbersResponse.FromString,
                )
        self.GetDrawnNumber = channel.unary_unary(
                '/bingo.BingoService/GetDrawnNumber',
                request_serializer=bingo__pb2.DrawnNumberRequest.SerializeToString,
                response_deserializer=bingo__pb2.DrawnNumber.FromString,
                )


class BingoServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Authenticate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Ready(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserBoard(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitMarkedNumbers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDrawnNumber(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BingoServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Authenticate': grpc.unary_unary_rpc_method_handler(
                    servicer.Authenticate,
                    request_deserializer=bingo__pb2.AuthenticateRequest.FromString,
                    response_serializer=bingo__pb2.AuthenticateResponse.SerializeToString,
            ),
            'Ready': grpc.unary_unary_rpc_method_handler(
                    servicer.Ready,
                    request_deserializer=bingo__pb2.ReadyRequest.FromString,
                    response_serializer=bingo__pb2.ReadyResponse.SerializeToString,
            ),
            'GetUserBoard': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserBoard,
                    request_deserializer=bingo__pb2.UserBoardRequest.FromString,
                    response_serializer=bingo__pb2.UserBoard.SerializeToString,
            ),
            'SubmitMarkedNumbers': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitMarkedNumbers,
                    request_deserializer=bingo__pb2.MarkedNumbersRequest.FromString,
                    response_serializer=bingo__pb2.MarkedNumbersResponse.SerializeToString,
            ),
            'GetDrawnNumber': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDrawnNumber,
                    request_deserializer=bingo__pb2.DrawnNumberRequest.FromString,
                    response_serializer=bingo__pb2.DrawnNumber.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'bingo.BingoService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class BingoService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Authenticate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/bingo.BingoService/Authenticate',
            bingo__pb2.AuthenticateRequest.SerializeToString,
            bingo__pb2.AuthenticateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Ready(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/bingo.BingoService/Ready',
            bingo__pb2.ReadyRequest.SerializeToString,
            bingo__pb2.ReadyResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetUserBoard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/bingo.BingoService/GetUserBoard',
            bingo__pb2.UserBoardRequest.SerializeToString,
            bingo__pb2.UserBoard.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SubmitMarkedNumbers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/bingo.BingoService/SubmitMarkedNumbers',
            bingo__pb2.MarkedNumbersRequest.SerializeToString,
            bingo__pb2.MarkedNumbersResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetDrawnNumber(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/bingo.BingoService/GetDrawnNumber',
            bingo__pb2.DrawnNumberRequest.SerializeToString,
            bingo__pb2.DrawnNumber.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
