# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: quiz.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nquiz.proto\x12\x04quiz\"\x07\n\x05\x45mpty\"\'\n\x07Student\x12\n\n\x02id\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"%\n\x0c\x41uthResponse\x12\x15\n\rauthenticated\x18\x01 \x01(\x08\"-\n\x08Question\x12\x10\n\x08question\x18\x01 \x01(\t\x12\x0f\n\x07options\x18\x02 \x03(\t\"\x18\n\x06\x41nswer\x12\x0e\n\x06\x61nswer\x18\x01 \x01(\x05\"\x19\n\x06Result\x12\x0f\n\x07\x63orrect\x18\x01 \x01(\x08\"?\n\x0b\x46inalResult\x12\x17\n\x0ftotal_questions\x18\x01 \x01(\x05\x12\x17\n\x0f\x63orrect_answers\x18\x02 \x01(\x05\x32\xca\x01\n\x0bQuizService\x12\x31\n\x0c\x41uthenticate\x12\r.quiz.Student\x1a\x12.quiz.AuthResponse\x12*\n\x0bGetQuestion\x12\x0b.quiz.Empty\x1a\x0e.quiz.Question\x12*\n\x0cSubmitAnswer\x12\x0c.quiz.Answer\x1a\x0c.quiz.Result\x12\x30\n\x0eGetFinalResult\x12\x0b.quiz.Empty\x1a\x11.quiz.FinalResultb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'quiz_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EMPTY._serialized_start=20
  _EMPTY._serialized_end=27
  _STUDENT._serialized_start=29
  _STUDENT._serialized_end=68
  _AUTHRESPONSE._serialized_start=70
  _AUTHRESPONSE._serialized_end=107
  _QUESTION._serialized_start=109
  _QUESTION._serialized_end=154
  _ANSWER._serialized_start=156
  _ANSWER._serialized_end=180
  _RESULT._serialized_start=182
  _RESULT._serialized_end=207
  _FINALRESULT._serialized_start=209
  _FINALRESULT._serialized_end=272
  _QUIZSERVICE._serialized_start=275
  _QUIZSERVICE._serialized_end=477
# @@protoc_insertion_point(module_scope)
